project:
  type: website
  output-dir: docs

website:
  title: "Iacchei Lab"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - team.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

